### ISSUE TITLE
Is there an updated compiled version for Windows?

### ISSUE THREAD

**Issue by rafaeldotjs** [nathan-osman/gimp-webp#12]
The entry in Gimp Plugin Registry dates back to 2011. Was it was ever updated?

**Comment by nathan-osman** [comment]
This plugin has been adapted and integrated into Gimp itself and will be available in the next release.

**Comment by rafaeldotjs** [comment]
Thank you for the quick reply. I've searched, but didn't find when that release will be. Do you have an estimate?

**Comment by nathan-osman** [comment]
I don't really have an estimate, but here's the page documenting what still needs to be completed before the next release: https://wiki.gimp.org/wiki/Roadmap#GIMP_2.10

**Comment by KrasnayaPloshchad** [comment]
GIMP 2.10 is coming now, so you just feel free to use that.

**Comment by rafaeldotjs** [comment]
Thanks!
