### ISSUE TITLE
Where Can I find The Gimp Dev Files

### ISSUE THREAD

**Issue by NoorMkdad** [nathan-osman/gimp-webp#13]
Hi, I have been searching all over the place but i can-not find those Dev Files for the life of me!

**Comment by NoorMkdad** [comment]
Wait I Just Found it, I Am sorry, would be nice to have a link to it

**Comment by NoorMkdad** [comment]
Nope Didnt find it :/
HELP

**Comment by nathan-osman** [comment]
Which platform are you using?

**Comment by NoorMkdad** [comment]
windows

**Comment by nathan-osman** [comment]
Hmm... I can't seem to find them either. It looks like the recommended approach now is to compile the Gimp using MSYS2.

**Comment by NoorMkdad** [comment]
Thank You.

**Comment by NoorMkdad** [comment]
I'l get the files and upload them to a repository to assist fellow windows users

**Comment by DanielIzquierdo** [comment]
for linux where do I find the gimp dev files?

**Comment by phw** [comment]
Ubuntu package libgimp2.0-dev
